
[general]
import = [
	"alacritty-theme/themes/gruvbox_dark.toml",
]

[window]
padding = { x = 5, y = 5 }
opacity = 0.75

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
size = 12.0

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", 'cd "$(cat ~/.terminal_dir 2>/dev/null || echo ~)"; exec zsh']

[colors.primary]
background = "0x32302f"
foreground = "0xd4be98"

[colors.normal]
black = "0x45403d"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x45403d"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

